# Generated by Django 4.0.4 on 2022-05-05 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='titre')),
                ('question_points', models.IntegerField(verbose_name='points')),
                ('difficulty', models.IntegerField(choices=[(0, '-----'), (1, 'Noob'), (2, 'Medium'), (3, 'Advanced'), (4, 'Hero')], default=0, verbose_name='niveau')),
                ('chrono', models.IntegerField(verbose_name='Temps max')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=64, verbose_name='réponse')),
                ('is_correct', models.BooleanField(default=False, verbose_name='correct')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='mise à jour')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='quiz.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Réponse',
            },
        ),
    ]
