# Generated by Django 4.0.3 on 2022-03-31 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('points', models.SmallIntegerField()),
                ('difficulty', models.IntegerField(choices=[(0, 'choisir'), (1, 'Noobs'), (2, 'Medium'), (3, 'Advanced'), (4, 'Hero')], default=0, verbose_name='Difficulté')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False, verbose_name='Correct')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mise à jour')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='quiz.question', verbose_name='Question')),
            ],
        ),
    ]
