# Generated by Django 4.0.3 on 2022-03-31 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='chrono',
            field=models.IntegerField(default=8),
        ),
    ]
