# Generated by Django 4.0.3 on 2022-04-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_question_chrono_alter_question_question_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='chrono',
            field=models.SmallIntegerField(verbose_name='Temps max'),
        ),
    ]
