# Generated by Django 4.0.3 on 2022-04-02 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_question_chrono'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Reponses'},
        ),
    ]
