# Generated by Django 4.0.3 on 2022-04-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_answer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Reponse'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=255, verbose_name='réponse'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'choisir'), (1, 'Noob'), (2, 'Medium'), (3, 'Advanced'), (4, 'Hero')], default=0, verbose_name='niveau'),
        ),
    ]
