# Generated by Django 4.0.6 on 2022-07-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_score_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=150, verbose_name='réponse'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(choices=[(0, '-----'), (1, 'Débutant'), (2, 'Intermédiaire'), (3, 'Avancé'), (4, 'Hero')], default=0, verbose_name='niveau'),
        ),
    ]
